[[check]]
type = "Exclude"
id = "STAN-0103"
scope = "all"

[[check]]
type = "Exclude"
id = "STAN-0005"
scope = "all"

[[check]]
type = "Exclude"
id = "STAN-0101"
# file = "src/NumHask/Array/Shape.hs"
scope = "all"

