resolver: lts-14.13

packages:
  - .
  - ../numhask/numhask
  - ../numhask/numhask-prelude
  - ../numhask/numhask-hedgehog

extra-deps:
  #- numhask-0.3.0.0
  #- numhask-prelude-0.3.1
  #- numhask-hedgehog-0.3
  - numhask-space-0.2.0
